# IMPORTANT: The version must match the version of docker-compose.yml
---
version: "3.8"

# All additional integrations should be added following this format only.

services:
  malware_tools_analyzers:
    image: khulnasoft/intelx_malware_tools_analyzers:${REACT_APP_INTELX_VERSION}
    container_name: intelx_malware_tools_analyzers
    restart: unless-stopped
    expose:
      - "4002"
    env_file:
      - env_file_integrations
    volumes:
      - generic_logs:/var/log/intelx
      - ../integrations/malware_tools_analyzers/clamav/etc:/etc/clamav
      - ../integrations/malware_tools_analyzers/clamav/sigs:/var/lib/clamav
      - ../integrations/malware_tools_analyzers/qiling/rootfs:/opt/deploy/rootfs
      - ../integrations/malware_tools_analyzers/qiling/profiles:/opt/deploy/profiles
    depends_on:
      - uwsgi

