version: '3.8'

services:
  postgres:
    env_file:
      - env_file_postgres_template
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2000M
          
  uwsgi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        REPO_DOWNLOADER_ENABLED: ${REPO_DOWNLOADER_ENABLED}
    image: khulnasoft/intelx:ci
    env_file:
      - env_file_app_ci

  
  daphne:
    image: khulnasoft/intelx:ci
    env_file:
      - env_file_app_ci
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M

  nginx:
    build:
      context: ..
      dockerfile: docker/Dockerfile_nginx
    image: khulnasoft/intelx_nginx:ci
    volumes:
      - ../configuration/nginx/http.conf:/etc/nginx/conf.d/default.conf
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M

  celery_beat:
    image: khulnasoft/intelx:ci
    env_file:
      - env_file_app_ci
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M

  celery_worker_default:
    image: khulnasoft/intelx:ci
    env_file:
      - env_file_app_ci
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M

  redis:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M