version: '3.8'

x-no-healthcheck: &no-healthcheck
  healthcheck:
    disable: true

services:
  uwsgi:
    image: khulnasoft/threatmatrix:${REACT_APP_THREATMATRIX_VERSION}
    container_name: threatmatrix_uwsgi
    volumes:
      - ../configuration/threat_matrix.ini:/etc/uwsgi/sites/threat_matrix.ini # uwsgi configuration file
      - ../configuration:/opt/deploy/threat_matrix/configuration
      - generic_logs:/var/log/threat_matrix
      - ../frontend/public/env.js:/var/www/reactapp/env.js # this is needed because we have to mount the file from the server to the image BEFORE staticfiles
      - static_content:/opt/deploy/threat_matrix/static
      - shared_files:/opt/deploy/files_required
    entrypoint:
      - ./docker/entrypoints/uwsgi.sh
    expose:
      - "8001"
    env_file:
      - env_file_app
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 8001 || exit 1" ]
      interval: 5s
      timeout: 2s
      start_period: 300s
      retries: 2

  daphne:
    image: khulnasoft/threatmatrix:${REACT_APP_THREATMATRIX_VERSION}
    container_name: threatmatrix_daphne
    restart: unless-stopped
    volumes:
      - generic_logs:/var/log/threat_matrix
      - shared_files:/opt/deploy/files_required
    entrypoint:
      - ./docker/entrypoints/daphne.sh
    expose:
      - "8011"
    env_file:
      - env_file_app
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8011 || exit 1"]
      interval: 5s
      timeout: 2s
      start_period: 2s
      retries: 6
    depends_on:
      uwsgi:
        condition: service_healthy

  nginx:
    image: khulnasoft/threatmatrix_nginx:${REACT_APP_THREATMATRIX_VERSION}
    container_name: threatmatrix_nginx
    restart: unless-stopped
    volumes:
      - ../configuration/nginx/websocket.conf:/etc/nginx/websocket.conf
      - ../configuration/nginx/errors.conf:/etc/nginx/errors.conf
      - ../configuration/nginx/http.conf:/etc/nginx/conf.d/default.conf
      - ../configuration/nginx/locations.conf:/etc/nginx/locations.conf
      - nginx_logs:/var/log/nginx
      - static_content:/var/www/static
    ports:
      - "80:80"
    depends_on:
      uwsgi:
        condition: service_healthy
      daphne:
        condition: service_healthy

  celery_beat:
    image: khulnasoft/threatmatrix:${REACT_APP_THREATMATRIX_VERSION}
    container_name: threatmatrix_celery_beat
    restart: unless-stopped
    volumes:
      - ../configuration:/opt/deploy/threat_matrix/configuration
      - generic_logs:/var/log/threat_matrix
      - shared_files:/opt/deploy/files_required
    entrypoint:
      - ./docker/entrypoints/celery_beat.sh
    env_file:
      - env_file_app
    <<: *no-healthcheck
    depends_on:
      uwsgi:
        condition: service_healthy


  celery_worker_default:
    image: khulnasoft/threatmatrix:${REACT_APP_THREATMATRIX_VERSION}
    container_name: threatmatrix_celery_worker_default
    restart: unless-stopped
    stop_grace_period: 3m
    volumes:
      - ../configuration:/opt/deploy/threat_matrix/configuration
      - generic_logs:/var/log/threat_matrix
      - shared_files:/opt/deploy/files_required
    entrypoint:
      - ./docker/entrypoints/celery_default.sh
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - env_file_app
    depends_on:
      uwsgi:
        condition: service_healthy
    <<: *no-healthcheck


volumes:
  postgres_data:
  nginx_logs:
  generic_logs:
  static_content:
  shared_files:
