# All additional integrations should be added following this format only.

services:
  tor_analyzers:
    image: khulnasoft/threatmatrix_tor_analyzers:${REACT_APP_THREATMATRIX_VERSION}
    container_name: threatmatrix_tor_analyzers
    restart: unless-stopped
    expose:
      - "4001"
    env_file:
      - env_file_integrations
    volumes:
      - generic_logs:/var/log/threat_matrix
    depends_on:
      - uwsgi
