services:
  uwsgi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        REPO_DOWNLOADER_ENABLED: ${REPO_DOWNLOADER_ENABLED}
        WATCHMAN: true
        PYCTI_VERSION: ${PYCTI_VERSION:-5.10.0}
    image: khulnasoft/threatmatrix:test
    volumes:
      - ../:/opt/deploy/threat_matrix
    environment:
      - DEBUG=True
      - DJANGO_TEST_SERVER=True
      - DJANGO_WATCHMAN_TIMEOUT=60

  daphne:
    image: khulnasoft/threatmatrix:test
    volumes:
      - ../:/opt/deploy/threat_matrix

  nginx:
    build:
      context: ..
      dockerfile: docker/Dockerfile_nginx
    image: khulnasoft/threatmatrix_nginx:test
    volumes:
      - ../configuration/nginx/django_server.conf:/etc/nginx/conf.d/default.conf

  celery_beat:
    image: khulnasoft/threatmatrix:test
    volumes:
      - ../:/opt/deploy/threat_matrix
    environment:
      - DEBUG=True

  celery_worker_default:
    image: khulnasoft/threatmatrix:test
    volumes:
      - ../:/opt/deploy/threat_matrix
    environment:
      - DEBUG=True
